# data
train_path: /Users/lining_zhang/Desktop/research/MIMIC/data/train_notes.txt
valid_path: /Users/lining_zhang/Desktop/research/MIMIC/data/valid_notes.txt
test_path: /Users/lining_zhang/Desktop/research/MIMIC/data/test_notes.txt

# model
model_path: /Users/lining_zhang/Desktop/research/MIMIC/model
vocab_obj_path: /Users/lining_zhang/Desktop/research/MIMIC/model/vocab_obj

# hps
embed_dim: 512 # 768/12 * 8
pad_index: 2
num_layers: 6
ffn_hidden: 768
n_head: 8
drop_prob: 0.1
eps: 1e-6

# train
batch_size: 8
num_epoch: 100
mask_prob: 0.15
learning_rate: 0.0001
is_train: True

# result
attn_path: /Users/lining_zhang/Desktop/research/MIMIC/model
label_path: /Users/lining_zhang/Desktop/research/MIMIC/data/spacy_syntax_pair.csv
pair_json_path: /Users/lining_zhang/Desktop/research/MIMIC/data/test_attention_pairs.json


#

# nohup /usr/bin/python -u main.py --config_file ./config/EGFR/config_EGFR_v0.yaml --version v0_0  >> logs/EGFR/EGFR_v0_0.log &
# nohup /usr/bin/python -u main.py --config_file ./config/EGFR/config_EGFR_v0.yaml --version v0_0 --mode test --restore_iters 12000 >> logs/EGFR/EGFR_v0_0_test.log &